# Generated by Django 3.2.8 on 2021-10-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodDrive', '0003_alter_appointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='badges',
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
